insert into trainers (name, gender, pokemon_id) values ('Aaron', 'M', 1)
insert into trainers (name, gender, pokemon_id) values ('Drake', 'M', 2)
insert into trainers (name, gender, pokemon_id) values ('Linda', 'F', 3)
insert into trainers (name, gender, pokemon_id) values ('Tom', 'M', 4)
insert into trainers (name, gender, pokemon_id) values ('Alyssa', 'F', 5)